### PR TITLE
Removed all .zip files from the git history

### PR DESCRIPTION
**Pull request by gavinhenderson**
Here is the process I went through to address #15 :

```
java -jar bfg-1.13.0.jar --delete-files *.zip Documents/mulberry-symbols.git
```

```
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

### CODE REVIEW

**Comment by gavinhenderson** [comment]
Hmm :thinking: I'm actually not sure if this works in a PR. If you look at my [repo](https://github.com/gavinhenderson/mulberry-symbols) it makes sense but I think it doesn't like being submitted as a PR because it wants to change the history.

**Comment by SteveALee** [comment]
Really? I thought last time I used bfg it makes a headless clone or some such and then replaces your origin repo with that. Bu tthen as I would have to had pushed to GH a merge might work as well.

I'll give the merge a go and see. Though might be simpler for me to just do what you did.

Thanks very much

**Comment by SteveALee** [comment]
I did a pull and it's still there for me 

`git checkout b4d49bdf3b750d3cacad56ccd3fdc25ee4287427^ -- mulberry-symbols.zip`

I also tried in a clean repository clone but still there :(

**Comment by SteveALee** [comment]
I htink you can only run bg against a repo so would need to reset the GH one to the new one created with bfg

**Comment by SteveALee** [comment]
I just run it myself and it seems to have now worked - the critical part is the clone --mirror as pushing this updates the GH repo

**Comment by gavinhenderson** [comment]
Ah well, you learn something new everyday :+1:

**Pull request merged**
