### PR TITLE
Added contents sidebar

### PR DESCRIPTION
**Pull request by gavinhenderson**
I have added a contents page. It is currently a work in progress but I just wanted your feedback.

Currently there are two independent scrolling areas. The sidebar disappears once the screen size reduces beyond a certain point. There are no presentation styles on the list or sidebar yet but I will add them once you okay what I have so far.

### CODE REVIEW

**Comment by SteveALee** [comment]
Thanks - it'll be a couple of days but I get to this ASAP. Thanks!

**Comment by SteveALee** [comment]
Looks good.

Nit - when I resize so list dissapears scrollbar moves to a strange place

**Comment by gavinhenderson** [comment]
@SteveALee Oh yes so it does, can see my mistake so its an easy fix. Ill finish up the side bar and ping you again when I'm done

**Comment by gavinhenderson** [comment]
@SteveALee Fixed that issue and styled the sidebar.

Happy for feedback and to iterate on what i've done :+1:

**Comment by SteveALee** [comment]
Looks great and I'd be happy to merge it now.

One minor thing I spotted when trying to change the context menu to download images is that the HTML template pulls in the website global stylesheet AND also defines it own inline styles.

I don't have any strong feelings but perhaps the categories page should use at least the website background colour? I'm also happy it is basically a standalone page with its own look, in which case the global sheet can be removed.

Any thoughts?

**Comment by gavinhenderson** [comment]
I had a brief think about this and I landed on the current solution. I can image 2 scenarios in which someone wants to access the HTML file.

1. Situation one is someone downloads it from the release and then I think it would be weird if it followed the website theme so I think this should just be plain white background with black text.
2. Situation two is through the webpage in which I think it makes sense to keep the consistent background color and text.

This is currently what happens. One problem with solution is when you open it from the release it will request the style sheet and get nothing but I don't see this as a huge issue.

**Comment by SteveALee** [comment]
I forgot it was in the release and not just the PDF there. It has some value there - eg can download from it.

Agree not finding the stylesheet not an issue and gives the desired behaviour :)

Are you ready for me to merge?

**Comment by SteveALee** [comment]
Actually the html is NOT in the release at present. It could be as a standalone HTML. But perhaps just PDF is less confusing.

**Comment by gavinhenderson** [comment]
@SteveALee Oh so its not, I don't know why I thought it was. I agree I don't think the HTML should be added to the release, PDF makes a lot more sense.

As it is only available on the website I think the current solution is the best.

**Comment by SteveALee** [comment]
What about styles being in 2 places? That's mildy confusing but I'm happy to leave as is.

I'll merge once you reply.

**Comment by gavinhenderson** [comment]
Hmm i agree it is mildly confusing but I think for now it works, happy to reconsider later if the template gets more complex

**Pull request merged**
